#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVER_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
PROJECTS_DIR="$(cd "${SERVER_DIR}/.." && pwd)"
FLUTTER_DIR="${FLUTTER_DIR:-${PROJECTS_DIR}/BB_flutter}"

DB_CONTAINER="${DB_CONTAINER:-bb-db}"
PGADMIN_CONTAINER="${PGADMIN_CONTAINER:-pgadmin}"
BACKEND_PORT="${BACKEND_PORT:-9090}"
FRONTEND_PORT="${FRONTEND_PORT:-7357}"
STOP_APP_PROCESSES="${STOP_APP_PROCESSES:-1}"
STOP_INFRA_CONTAINERS="${STOP_INFRA_CONTAINERS:-1}"

LOG_DIR_SERVER="${SERVER_DIR}/.logs"
LOG_DIR_FLUTTER="${FLUTTER_DIR}/.logs"
BACKEND_META_FILE="${LOG_DIR_SERVER}/backend.meta"
FRONTEND_META_FILE="${LOG_DIR_FLUTTER}/frontend.meta"
ACTIVE_MODE_FILE="${LOG_DIR_SERVER}/active-mode.txt"
SERVER_RUNTIME_MODE_FILE="${SERVER_DIR}/src/generated/runtimeMode.ts"
FLUTTER_RUNTIME_MODE_FILE="${FLUTTER_DIR}/lib/generated/runtime_mode.g.dart"

log() {
  echo "[dev-stop] $1"
}

has_cmd() {
  command -v "$1" >/dev/null 2>&1
}

read_meta_value() {
  local file="$1"
  local key="$2"
  if [[ ! -f "${file}" ]]; then
    return 0
  fi
  awk -F'=' -v k="${key}" '$1 == k {print substr($0, index($0, "=") + 1)}' "${file}" | tail -n 1
}

kill_pid_if_alive() {
  local pid="$1"
  local label="$2"
  if [[ -z "${pid}" ]]; then
    return 0
  fi
  if kill -0 "${pid}" >/dev/null 2>&1; then
    log "Stopping ${label} (pid=${pid})..."
    kill "${pid}" >/dev/null 2>&1 || true
    sleep 1
    if kill -0 "${pid}" >/dev/null 2>&1; then
      log "${label} still alive, forcing stop..."
      kill -9 "${pid}" >/dev/null 2>&1 || true
    fi
  fi
}

stop_from_pid_file() {
  local pid_file="$1"
  local label="$2"
  if [[ -f "${pid_file}" ]]; then
    local pid
    pid="$(cat "${pid_file}" 2>/dev/null || true)"
    kill_pid_if_alive "${pid}" "${label}"
    rm -f "${pid_file}"
  fi
}

stop_listening_process_if_matches() {
  local port="$1"
  local label="$2"
  local regex="$3"
  local pid
  pid="$(lsof -nP -tiTCP:"${port}" -sTCP:LISTEN 2>/dev/null | head -n 1 || true)"
  if [[ -z "${pid}" ]]; then
    return 0
  fi

  local cmd
  cmd="$(ps -p "${pid}" -o command= 2>/dev/null || true)"
  if [[ "${cmd}" =~ ${regex} ]]; then
    kill_pid_if_alive "${pid}" "${label} (port ${port})"
  else
    log "Port ${port} is used by another process. Skipping kill: ${cmd}"
  fi
}

stop_matching_processes() {
  local label="$1"
  local regex="$2"
  local pids
  pids="$(pgrep -f "${regex}" || true)"
  if [[ -z "${pids}" ]]; then
    return 0
  fi

  while IFS= read -r pid; do
    [[ -z "${pid}" ]] && continue
    kill_pid_if_alive "${pid}" "${label}"
  done <<< "${pids}"
}

stop_container_if_running() {
  local name="$1"
  if ! docker container inspect "${name}" >/dev/null 2>&1; then
    log "Container '${name}' does not exist. Skipping."
    return
  fi

  local running
  running="$(docker inspect -f '{{.State.Running}}' "${name}")"
  if [[ "${running}" == "true" ]]; then
    log "Stopping container '${name}'..."
    docker stop "${name}" >/dev/null
  else
    log "Container '${name}' is already stopped."
  fi
}

write_stopped_mode_files() {
  local service_status="$1"
  local frontend_api_mode="$2"
  local backend_db_mode="$3"
  local frontend_app_env="$4"
  local backend_env_name="$5"
  local generated_at_iso
  generated_at_iso="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

  mkdir -p "${LOG_DIR_SERVER}"
  cat > "${ACTIVE_MODE_FILE}" <<EOF
Status: ${service_status}
Frontend API Mode: ${frontend_api_mode}
Backend DB Mode: ${backend_db_mode}
Frontend APP_ENV: ${frontend_app_env}
Backend ENV_FILE: ${backend_env_name}
Frontend Port: ${FRONTEND_PORT}
Backend Port: ${BACKEND_PORT}
Timestamp: $(date +"%Y-%m-%d %H:%M:%S %Z")
EOF
  log "Wrote stopped status file: ${ACTIVE_MODE_FILE}"

  mkdir -p "$(dirname "${SERVER_RUNTIME_MODE_FILE}")"
  cat > "${SERVER_RUNTIME_MODE_FILE}" <<EOF
// AUTO-GENERATED BY scripts/stop_full_dev_environment.sh
// Do not edit manually.
export const runtimeMode = {
  serviceStatus: '${service_status}',
  frontendApiMode: '${frontend_api_mode}',
  backendDbMode: '${backend_db_mode}',
  frontendAppEnv: '${frontend_app_env}',
  backendEnvFile: '${backend_env_name}',
  frontendPort: ${FRONTEND_PORT},
  backendPort: ${BACKEND_PORT},
  generatedAt: '${generated_at_iso}',
} as const;
EOF
  log "Wrote server runtime mode file: ${SERVER_RUNTIME_MODE_FILE}"

  mkdir -p "$(dirname "${FLUTTER_RUNTIME_MODE_FILE}")"
  cat > "${FLUTTER_RUNTIME_MODE_FILE}" <<EOF
// AUTO-GENERATED BY /Users/dwrwnlwy/projects/BB_server/scripts/stop_full_dev_environment.sh
// Do not edit manually.
const String kRuntimeServiceStatus = '${service_status}';
const String kRuntimeFrontendApiMode = '${frontend_api_mode}';
const String kRuntimeBackendDbMode = '${backend_db_mode}';
const String kRuntimeFrontendAppEnv = '${frontend_app_env}';
const String kRuntimeBackendEnvFile = '${backend_env_name}';
const int kRuntimeFrontendPort = ${FRONTEND_PORT};
const int kRuntimeBackendPort = ${BACKEND_PORT};
const String kRuntimeGeneratedAt = '${generated_at_iso}';
EOF
  log "Wrote flutter runtime mode file: ${FLUTTER_RUNTIME_MODE_FILE}"
}

main() {
  if ! has_cmd lsof; then
    echo "[dev-stop] ERROR: lsof command not found."
    exit 1
  fi

  local frontend_api_mode backend_db_mode frontend_app_env backend_env_name
  frontend_api_mode="$(read_meta_value "${FRONTEND_META_FILE}" "API_MODE")"
  backend_db_mode="$(read_meta_value "${BACKEND_META_FILE}" "MODE")"
  frontend_app_env="$(read_meta_value "${FRONTEND_META_FILE}" "APP_ENV")"
  backend_env_name="$(basename "$(read_meta_value "${BACKEND_META_FILE}" "ENV_FILE")")"

  frontend_api_mode="${frontend_api_mode:-unknown}"
  backend_db_mode="${backend_db_mode:-unknown}"
  frontend_app_env="${frontend_app_env:-unknown}"
  backend_env_name="${backend_env_name:-unknown}"

  if [[ "${STOP_APP_PROCESSES}" == "1" ]]; then
    kill_pid_if_alive "$(read_meta_value "${BACKEND_META_FILE}" "PID")" "backend"
    stop_from_pid_file "${LOG_DIR_SERVER}/backend-dev.pid" "backend-dev"
    stop_from_pid_file "${LOG_DIR_SERVER}/backend-prod.pid" "backend-prod"
    stop_listening_process_if_matches "${BACKEND_PORT}" "backend" "(node|ts-node|tsx|npm)"
    stop_matching_processes "backend-orphan" "${SERVER_DIR}/node_modules/.bin/ts-node-dev.*src/server.ts"
    rm -f "${BACKEND_META_FILE}"

    kill_pid_if_alive "$(read_meta_value "${FRONTEND_META_FILE}" "PID")" "frontend"
    stop_from_pid_file "${LOG_DIR_FLUTTER}/flutter-web-local.pid" "flutter-web-local"
    stop_from_pid_file "${LOG_DIR_FLUTTER}/flutter-web-prod.pid" "flutter-web-prod"
    stop_listening_process_if_matches "${FRONTEND_PORT}" "frontend" "(flutter|dart)"
    stop_matching_processes "frontend-orphan" "flutter run -d chrome --web-port ${FRONTEND_PORT}"
    rm -f "${FRONTEND_META_FILE}"
  else
    log "Skipping frontend/backend stop because STOP_APP_PROCESSES=${STOP_APP_PROCESSES}."
  fi

  if [[ "${STOP_INFRA_CONTAINERS}" == "1" ]]; then
    if has_cmd docker && docker info >/dev/null 2>&1; then
      stop_container_if_running "${PGADMIN_CONTAINER}"
      stop_container_if_running "${DB_CONTAINER}"
    else
      log "Docker not running. Skipping container stop."
    fi
  else
    log "Skipping DB/pgAdmin container stop because STOP_INFRA_CONTAINERS=${STOP_INFRA_CONTAINERS}."
  fi

  local service_status="stopped"
  if [[ "${STOP_APP_PROCESSES}" == "1" && "${STOP_INFRA_CONTAINERS}" == "0" ]]; then
    service_status="infra_only"
  elif [[ "${STOP_APP_PROCESSES}" == "0" && "${STOP_INFRA_CONTAINERS}" == "1" ]]; then
    service_status="app_only"
  fi

  write_stopped_mode_files "${service_status}" "${frontend_api_mode}" "${backend_db_mode}" "${frontend_app_env}" "${backend_env_name}"
  log "Done. Service status is now: ${service_status}."
}

main "$@"
